"status: needs triage":
  - '/.*/'
"scope: api":
  - '(Devopness API)'
"scope: website":
  - '(Devopness website)'
"scope: web-app":
  - '(Devopness web app)'
"scope: docs":
  - '(Documentation)'
"scope: sdk":
  - 'SDK-'
"scope: sdk-javascript":
  - '(SDK-JS)'
