"scope: ci":
  - changed-files: .github/**/*

"scope: application":
  - changed-files: applications/**/*

"scope: docs":
  - changed-files: docs/**/*

"scope: packages":
  - changed-files: packages/**/*

"scope: repo":
  - changed-files: "*"

"scope: sdks":
  - changed-files:  packages/sdks/**/*

"scope: sdk-javascript":
  - changed-files: packages/sdks/javascript/**/*
