"scope: ci":
  - ".github/**/*"

"scope: application":
  - applications/**/*

"scope: docs":
  - docs/**/*

"scope: packages":
  - packages/**/*

"scope: repo":
  - "*"

"scope: sdks":
  - packages/sdks/**/*

"scope: sdk-javascript":
  - packages/sdks/javascript/**/*
