"scope: ci":
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**/*"

"scope: application":
  - changed-files:
    - any-glob-to-any-file:
      - applications/**/*

"scope: docs":
  - changed-files:
    - any-glob-to-any-file:
      - docs/**/*

"scope: packages":
  - changed-files:
    - any-glob-to-any-file:
      - packages/**/*

"scope: repo":
  - changed-files:
    - any-glob-to-any-file:
      - "*"

"scope: sdks":
  - changed-files:
    - any-glob-to-any-file:
      - packages/sdks/**/*

"scope: sdk-javascript":
  - changed-files:
    - any-glob-to-any-file:
      - packages/sdks/javascript/**/*
