"scope: ci":
  - ".github/**/*"

"scope: applications":
  - applications/**/*

"scope: docs":
  - docs/**/*

"scope: packages":
  - packages/**/*

"scope: repo":
  - "*"

"scope: sdk":
  - packages/sdks/**/*

"scope: sdk-javascript":
  - packages/sdks/javascript/**/*
