type: object
properties:
  id:
    type: integer
    description: The unique id of the given record
    example: 3
  name:
    type: string
    description: The pipeline's name
    example: 'my pipeline'
  resource_type:
    type: string
    description: The pipeline's resource type
    example: "application"
  resource_id:
    type: integer
    description: The pipeline's resource id
    example: 435
  project_id:
    type: integer
    description: The pipeline's project id
    example: 94
  created_by:
    type: integer
    description: id of the user responsible for creating the pipeline
    example: 23
  created_at:
    type: string
    format: date-time
    description: The date and time when the record was created
    example: '2019-09-25T15:50:48.000000Z'
  updated_at:
    type: string
    format: date-time
    description: The date and time when the record was last updated
    example: '2019-09-25T13:52:04.000000Z'
required:
  - id
  - name
  - resource_type
  - resource_id
  - project_id
  - created_by
  - updated_at
  - created_at
