summary: Returns a list of all deployments belonging to an application
tags:
  - Applications - Deployments
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: application_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the application to get deployments from
responses:
  200:
    description: 'Ok'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Deployments'
