summary: Create a new SSL certificate linked to the current application
operationId: addSslCertificateToApplication
tags:
  - Applications - SSL Certificates
parameters:
  - $ref: "#/components/parameters/acceptHeader"
  - $ref: "#/components/parameters/authHeader"
  - $ref: "#/components/parameters/contentTypeHeader"
  - in: path
    name: application_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Unique id of the parent application
requestBody:
  description: A JSON object containing data for creating a new record of SSL certificate
  required: true
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/SslCertificateCreate"
responses:
  201:
    description: 'Created'
    headers:
      X-Devopness-Action-Id:
        schema:
          type: integer
        description: The dispatched action id of the resource
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/SslCertificate"
  404:
    $ref: "#/components/responses/NotFound"
