summary: Delete a given application
operationId: deleteApplication
tags:
  - Applications
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: application_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the application to be deleted
responses:
  204:
    description: 'Ok'
  404:
    $ref: '#/components/responses/NotFound'
