summary: "Create a new application"
operationId: addApplicationToProject
tags:
  - Projects - Applications
parameters:
  - $ref: "#/components/parameters/acceptHeader"
  - $ref: "#/components/parameters/authHeader"
  - $ref: "#/components/parameters/contentTypeHeader"
  - in: path
    name: project_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the project to which the application will be added
requestBody:
  description: A JSON object containing project data
  required: true
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/ApplicationCreate"
responses:
  201:
    description: "Created"
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Application"
  422:
    $ref: "#/components/responses/ValidationError"
