title: '[Feature request]: '
labels: ['type: enhancement']
body:
  - type: textarea
    attributes:
      label: Problem to be solved
      description: |
        A clear and concise description of what the problem is.
      placeholder: "e.g: I'm always frustrated when I try to [...] but [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why does this matter?
      description: |
        Tell us why you believe your request is important to the project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
