type: object
properties:
  id:
    type: integer
    description: Unique id of the given record
    example: 16523
  name:
    type: string
    description: Environment's name
    example: 'produção'
  type:
    $ref: '#/components/schemas/EnvironmentType'
    description: The type of the deployment being triggered
  servers:
    $ref: '#/components/schemas/Servers'
  created_at:
    type: string
    format: date-time
    description: The date and time when the record was created
    example: '2019-09-25 13:49:51'
  updated_at:
    type: string
    format: date-time
    description: The date and time when the record was last updated
    example: '2019-09-25 13:52:04'
required:
  - id
  - name
  - type
