type: object
properties:
  id:
    description: Environment's unique id
    example: 867
    type: integer
  name:
    type: string
    description: The environment's name
    example: my project - staging
  type:
    $ref: '#/components/schemas/EnvironmentType'
required:
  - name
  - type
