//! Rendering `bugs.toml` into its Markdown mirror.
//!
//! Kept apart from the data model so the register can be loaded and validated
//! without pulling in presentation, and so the mirror's shape is visible in one
//! place.

use std::fmt::Write as _;

use tetanus_config::bugs::{Bug, BugStatus, Bugs};

/// Every mirror this register owns, with the content each should hold.
pub fn render_all(bugs: &Bugs) -> Vec<(&'static str, String)> {
    vec![("BUGS.md", render(bugs))]
}

pub fn render(bugs: &Bugs) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "# Known defects");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated from `.tetanus/bugs.toml`. Do not edit this file: a change here is"
    );
    let _ = writeln!(
        out,
        "overwritten by `tetanus bugs generate`, and `tetanus bugs check` fails when the"
    );
    let _ = writeln!(out, "two disagree. Edit the register instead.");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Scope: defects in this repository's own source. A vulnerability in a dependency \
         is reported to whoever publishes it, not here; see `.github/SECURITY.md` for how \
         to disclose one."
    );
    let _ = writeln!(out);

    let open = bugs.count(BugStatus::Open);
    let _ = writeln!(
        out,
        "{open} open, {} fixed, {} accepted.",
        bugs.count(BugStatus::Fixed),
        bugs.count(BugStatus::Accepted)
    );
    let _ = writeln!(out);

    for (title, status) in [
        ("Open", BugStatus::Open),
        ("Accepted", BugStatus::Accepted),
        ("Fixed", BugStatus::Fixed),
    ] {
        let selected: Vec<&Bug> = bugs.bugs.iter().filter(|b| b.status == status).collect();
        if selected.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## {title}");
        let _ = writeln!(out);
        for bug in selected {
            render_bug(&mut out, bug);
        }
    }

    out
}

fn render_bug(out: &mut String, bug: &Bug) {
    let _ = writeln!(out, "### {} — {}", bug.id, bug.summary);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "`{}` · {} · {}",
        bug.kind.as_str(),
        bug.severity.as_str(),
        bug.confidence.as_str()
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", bug.evidence);
    let _ = writeln!(out);
    if let Some(rationale) = &bug.rationale {
        let _ = writeln!(out, "Not being fixed because: {rationale}");
        let _ = writeln!(out);
    }
    let mut locations: Vec<&String> = bug.location.iter().collect();
    locations.sort();
    let _ = writeln!(out, "Location:");
    let _ = writeln!(out);
    for location in locations {
        let _ = writeln!(out, "- `{location}`");
    }
    let _ = writeln!(out);
}
