//! Rendering `living.toml` into its human-readable mirrors.
//!
//! `CHANGELOG.md`, `HANDOVER.md` and `SESSION.md` are projections. They are
//! rendered deterministically and drift-checked, so hand-editing one is
//! detected rather than tolerated. Anything a person needs to say that does not
//! belong in the state belongs in `living.toml`.

use tetanus_config::living::{Living, WorkStatus};

/// Banner marking a file as generated. Drift-checking a file without it is an
/// error, because the point of the marker is to make the ownership obvious to
/// the next person who opens the file.
const BANNER: &str =
    "<!-- Generated by `tetanus living generate` from living.toml. Do not edit by hand. -->";

fn heading(levels: usize, text: &str) -> String {
    format!("{} {}", "#".repeat(levels), text)
}

pub fn render_changelog(living: &Living) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push_str("\n\n");
    out.push_str(&heading(1, "Engineering changelog"));
    out.push('\n');
    out.push_str(
        "Records engineering-state changes, not product releases. Product release notes are in each \
         package's own `CHANGELOG.md`, which Changesets owns.\n\n",
    );

    let mut sessions: Vec<_> = living.session.iter().collect();
    sessions.sort_by(|a, b| b.date.cmp(&a.date));

    for session in sessions {
        out.push_str(&heading(2, &format!("{} — {}", session.date, session.id)));
        out.push('\n');
        out.push_str(&session.summary);
        out.push('\n');

        if !session.touched.is_empty() {
            out.push_str("\n### Scope\n\n");
            for path in &session.touched {
                out.push_str(&format!("- `{path}`\n"));
            }
        }
        if !session.ratchet_outcome.is_empty() {
            out.push_str("\n### Ratchet outcome\n\n");
            out.push_str("| Ratchet | Outcome |\n| --- | --- |\n");
            for (id, outcome) in &session.ratchet_outcome {
                out.push_str(&format!("| `{id}` | {outcome} |\n"));
            }
        }
        if let Some(notes) = &session.notes {
            out.push('\n');
            out.push_str(notes);
            out.push('\n');
        }
        out.push('\n');
    }

    out
}

pub fn render_handover(living: &Living) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push_str("\n\n");
    out.push_str(&heading(1, "Handover"));
    out.push('\n');
    out.push_str(&format!(
        "Project: **{}** · phase: **{}** · substrate: `{}`\n\n",
        living.project.name,
        living.phase.as_str(),
        living.project.engineering_substrate
    ));

    out.push_str(&heading(2, "Current focus"));
    out.push('\n');
    match &living.handover.current_focus {
        Some(focus) => {
            out.push_str(focus);
            out.push('\n');
        }
        None => out.push_str("_No focus recorded._\n"),
    }

    out.push('\n');
    out.push_str(&heading(2, "Active work"));
    out.push('\n');
    let active: Vec<_> = living.active_work().collect();
    if active.is_empty() {
        out.push_str("_No active work items._\n");
    } else {
        for item in active {
            out.push_str(&format!("- **{}** — {}\n", item.id, item.summary));
            if !item.scope.is_empty() {
                out.push_str(&format!("  - Scope: {}\n", item.scope.join(", ")));
            }
            if let Some(notes) = &item.notes {
                out.push_str(&format!("  - Notes: {notes}\n"));
            }
        }
    }

    out.push('\n');
    out.push_str(&heading(2, "Next actions"));
    out.push('\n');
    if living.handover.next_actions.is_empty() {
        out.push_str("_None recorded._\n");
    } else {
        for (index, action) in living.handover.next_actions.iter().enumerate() {
            out.push_str(&format!("{}. {action}\n", index + 1));
        }
    }

    let blocked: Vec<_> = living
        .work
        .iter()
        .filter(|w| w.status == WorkStatus::Blocked)
        .collect();
    if !blocked.is_empty() {
        out.push('\n');
        out.push_str(&heading(2, "Blocked"));
        out.push('\n');
        for item in blocked {
            out.push_str(&format!(
                "- **{}** — {} ({})\n",
                item.id,
                item.summary,
                item.notes.as_deref().unwrap_or("no reason recorded")
            ));
        }
    }

    if !living.blockers.is_empty() {
        out.push('\n');
        out.push_str(&heading(2, "Blockers"));
        out.push('\n');
        for blocker in &living.blockers {
            out.push_str(&format!(
                "- **{}** — {}{}\n",
                blocker.id,
                blocker.summary,
                blocker
                    .owner
                    .as_ref()
                    .map(|o| format!(" (owner: {o})"))
                    .unwrap_or_default()
            ));
        }
    }

    if !living.decisions.is_empty() {
        out.push('\n');
        out.push_str(&heading(2, "Decisions"));
        out.push('\n');
        let mut decisions: Vec<_> = living.decisions.iter().collect();
        decisions.sort_by(|a, b| a.id.cmp(&b.id));
        for decision in decisions {
            out.push_str(&format!(
                "- **{}** {} — {}\n",
                decision.id, decision.title, decision.rationale
            ));
        }
    }

    if !living.handover.cautions.is_empty() {
        out.push('\n');
        out.push_str(&heading(2, "Cautions"));
        out.push('\n');
        for caution in &living.handover.cautions {
            out.push_str(&format!("- {caution}\n"));
        }
    }

    out
}

pub fn render_session(living: &Living) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push_str("\n\n");
    out.push_str(&heading(1, "Session"));
    out.push('\n');

    let Some(latest) = living.latest_session() else {
        out.push_str("_No session recorded._\n");
        return out;
    };

    out.push_str(&format!("**{}** · {}\n\n", latest.id, latest.summary));

    out.push_str(&heading(2, "Scope"));
    out.push('\n');
    if latest.scope.is_empty() {
        out.push_str("_No scope recorded._\n");
    } else {
        for path in &latest.scope {
            out.push_str(&format!("- {path}\n"));
        }
    }

    out.push('\n');
    out.push_str(&heading(2, "Files touched"));
    out.push('\n');
    if latest.touched.is_empty() {
        out.push_str("_None recorded._\n");
    } else {
        for path in &latest.touched {
            out.push_str(&format!("- `{path}`\n"));
        }
    }

    if !latest.ratchet_outcome.is_empty() {
        out.push('\n');
        out.push_str(&heading(2, "Ratchet outcome"));
        out.push('\n');
        out.push_str("| Ratchet | Baseline | Measured | Verdict |\n| --- | --- | --- | --- |\n");
        for (id, outcome) in &latest.ratchet_outcome {
            out.push_str(&format!("| `{id}` | | | {outcome} |\n"));
        }
    }

    if let Some(notes) = &latest.notes {
        out.push('\n');
        out.push_str(&heading(2, "Notes"));
        out.push('\n');
        out.push_str(notes);
        out.push('\n');
    }

    out.push('\n');
    out.push_str(&heading(2, "Objectives"));
    out.push('\n');
    for objective in &living.objectives {
        out.push_str(&format!(
            "- **{}** ({:?}) — {}\n",
            objective.id, objective.status, objective.statement
        ));
    }

    out
}

pub fn render_all(living: &Living) -> Vec<(&'static str, String)> {
    vec![
        ("CHANGELOG.md", render_changelog(living)),
        ("HANDOVER.md", render_handover(living)),
        ("SESSION.md", render_session(living)),
    ]
}
