summary: Send invitation to user email to participate to a project's environment
operationId: sendInvitation
tags:
  - Environments - Invitations
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the environment to invite a user
requestBody:
  description: A JSON object containing the email to send the invitation
  required: true
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/InvitationCreate'
responses:
  201:
    description: 'Created'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Invitation'
  403:
    $ref: '#/components/responses/Forbidden'
  422:
    $ref: '#/components/responses/ValidationError'
