# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create `.env` file
        # DEV_API_DOCS_ENV_FILE: contents of a `.env` to be used when executing this job
        run: |
          echo "${{ secrets.DEV_API_DOCS_ENV_FILE }}" > .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download latest API generated docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: npm run api-docs-zip-download

      - name: Extract downloaded content
        run: npm run api-docs-zip-extract

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update API generated files"
          file_pattern: "docs/spec/*"

      - name: Build API Docs
        run: npm run build
