type: object
properties:
  id:
    type: integer
    description: The unique id of the given record
    example: 45678
  project_id:
    type: integer
    description: The id of the project this role belongs to
    example: 984123
  name:
    type: string
    description: The role's name
    example: "admin"
  description:
    type: string
    description: Description of this role
    example: "Has total access to resources"
    nullable: true
  permissions:
    $ref: "#/components/schemas/RolePermissions"
  created_at:
    type: string
    format: date-time
    description: The date and time when the record was created
    example: "2019-09-25T15:50:48.000000Z"
  updated_at:
    type: string
    format: date-time
    description: The date and time when the record was last updated
    example: "2019-09-25T13:52:04.000000Z"
required:
  - id
  - project_id
  - name
  - description
  - permissions
  - created_at
  - updated_at
