summary: Replace all linked servers by new ones. Immediately deploying all changes to previously and newly linked servers
operationId: replaceLinkedServers
tags:
  - Environments - Servers
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Unique ID of the environment
requestBody:
  description: A JSON object containing environment server link parameters
  required: true
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/EnvironmentLinkItem'
responses:
  201:
    $ref: '#/components/responses/NoContent'
  404:
    $ref: '#/components/responses/NotFound'
