summary: Creates a team and link it to the given environment
operationId: addTeamToEnvironment
tags:
  - Environments - Teams
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: The numeric environment ID
requestBody:
  description: A JSON object containing team data
  required: true
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/TeamCreate'
responses:
  201:
    description: 'Created'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Team'
  422:
    $ref: '#/components/responses/ValidationError'
