summary: Unlink team from the environment
operationId: unlinkTeamFromEnvironment
tags:
  - Teams
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the environment to unlink
  - in: path
    name: team_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the team to be unlinked
responses:
  204:
    $ref: '#/components/responses/NoContent'
  403:
    $ref: '#/components/responses/Forbidden'
