name: 🐞 Bug Report
description: Report a bug/issue on Devopness platform, website, SDKs or documentation
title: '[Bug]: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
         **To report a Devopness security vulnerability, please [send an email to `social@devopness.com`](mailto:social@devopness.com) with all the details.**

         ⚠️ Do **NOT** create a public issue on GitHub for security vulnerabilities. See our [security policy]( <LINK TO BE UPDATED SOON>) for more details. ⚠️
  - type: dropdown
    attributes:
      label: Which Devopness module(s) are the source of the bug?
      options:
        - Devopness API
        - Devopness website
        - Devopness web app
        - Documentation
        - SDK-JS
        - Don't know / other
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: SDK Version
      description: |
        If your issue is SDK related, please inform the SDK/npm package version being used when the bug was detected. E.g.: 0.9.3.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is actually happening?
      description: |
        A clear and concise description of what is actually happening.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction link
      description: |
        If you're having issues consuming one of our SDKs, a link to real code in jsfiddle.net, codesandbox.io etc is very helpful to speed up bug reproduction and resolution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
      Steps to reproduce the behavior:
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional details
      description: |
      Browser version, framework being used, where is the SDK being consumed from (Node.js, Browser, ReactNative, ...). If applicable, add screenshots to help explain your problem.
    validations:
      required: false
