name: 🐞 Bug Report
description: Report a bug/issue on Devopness platform, website, SDKs or documentation
title: '[Bug]: '
labels: ['type: bug']
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report 🐞

        Thanks for taking the time to fill out this bug report!

        Please answer each question below to your best ability.

        To report a Devopness security vulnerability, please make a submission to our [Security Advisory vulnerability report](https://github.com/devopness/devopness/security/advisories/new).

        ⚠️ Do **NOT** create a public issue on GitHub for security vulnerabilities. See our [security policy](https://github.com/devopness/devopness/security/policy) for more details. ⚠️
  - type: textarea
    attributes:
      label: "Problem: What is happening?"
      description: |
        A clear and concise description of what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which Devopness module(s) are the source of the bug?
      options:
        - Devopness API
        - Devopness website
        - Devopness web app
        - Documentation
        - SDK-JS
        - UI - Design System / React components
        - Don't know / other
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: Package Version
      description: |
        If your issue is related to a package, such as `SDK-JS` or `UI - Design System / React Components`, please inform the package version being used when the bug was detected. E.g.: 0.9.3.
    validations:
      required: false
  - type: input
    attributes:
      label: Reproduction link
      description: |
        If you're having issues consuming one of our SDKs, a link to real code in jsfiddle.net, codesandbox.io etc is very helpful to speed up bug reproduction and resolution
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional details
      description: |
        Browser version, framework being used, where is the SDK being consumed from (Node.js, Browser, ReactNative, ...). If applicable, add screenshots to help explain your problem.
    validations:
      required: false
