openapi: "3.0.0"
info:
  version: "latest"
  title: devopness API
  x-logo:
    url: https://staging.devopness.com/26f9f5be5cd326a0ad0cc4f4ed65129b.png
  description: |
    This page contains the documentation on how to use `devopness` through API calls.
    > Note: This documentation is not complete, so for missing parts or inaccurate API description please
    >
    > reach out to `devopness` API team.

    # API Reference

    ## Introduction
    devopness's API exposes all `devopness` features via a standardized programmatic interface. Using devopness's API, you can perform every operation you can do on devopness.com web interfaces and mobile apps.

    ## Getting started
    All you need to obtain a token and start consuming this API is a valid email/password registered with devopness.com.


    The `devopness` API is based on HTTPS requests and JSON responses, organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable resource-oriented URLs, accepts requests with [JSON-encoded](http://www.json.org/) bodies with arguments, returns [JSON-encoded](http://www.json.org/) responses, and uses standard HTTP response codes, authentication, and verbs.

    ## Date format
    All dates in the API use UTC and are strings in the [ISO 8601 "combined date and time representation" format](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations):
    ```
    2015-05-15 15:50:38
    ```

    ## Errors
    The devopness API uses standard HTTP status codes to indicate the success or failure of an API call. In general: Codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error that failed given the information provided (e.g., a required parameter was omitted). Codes in the `5xx` range indicate an error on the API servers and are very rare.

    The body of the error response is a JSON in the following format:

    ```
    {
      "message": "The given request data was invalid"
      "errors": { // Optional errors object, returned only when there are detailed error message to be shared
          "field_1": [
              "Optional error message related to field_1"
          ],
          "field_2": [
              "Optional error message related to field_2"
          ],
      }
    }
    ```

    ## Responses
    When a request is successful, a response body will typically be sent back in the form of a JSON object.
    Exception to this rule is when a DELETE request is processed, which will result in a successful HTTP 204 status and an empty response body.

    ### Response codes
    Response codes indicate success or failure of request processing.
    Status codes from the `2xx` range indicate that request has been accepted.
    If the returned code is from the `4xx` or `5xx` range then it reveals either problem with the request or unability to process data.
    See below for a list of HTTP Status codes used by `devopness` API:

    | Status Code   | Description   |
    | -------------:|---------------|
    | 200           | Ok - The request was successful
    | 201           | Created - The request was successful and a new resource has been created as a result
    | 202           | Accepted - The request has been received but not yet completely processed
    | 204           | No content - The request was successful. There is no content to return, but the headers may be useful
    | 400           | Bad Request - The server could not understand the request due to invalid syntax
    | 401           | Unauthenticated - It is usally caused by using wrong or expired credentials
    | 403           | Forbidden/Unauthorized - The used credentials do not allow access to the resource
    | 404           | Not Found - The server cannot find the requested resource
    | 405           | Method not allowed - The request method has been disabled and cannot be used
    | 409           | Conflict - The current request conflicts with the current state of the server
    | 415           | Unsupported Media Type - The request's `Content-Type` or `Accept` headers are not set to a valid format
    | 422           | Unprocessable Entity - The request was unable to be processed due to validation errors
    | 429           | Too many requests - The client exceeded the requests limit in a window of time
    | 500           | Internal Server Error. Please contact the `devopness` team

    ## Routes and Endpoints
    A route is a URI which can be mapped to different HTTP methods. The mapping of an individual HTTP method to a route is known as an endpoint. `devopness` API exposes, as much as posible, well standardized endpoints with resources and segments leading the path to access the desired resource data.

    Each resource mentioned in an endpoint segment has its name written in the plural form, as we are always referencing a collection of objects, that might or might not be filtered by a single ID or extra query string parameters.

    ### Resources and nested resources endpoints
    Basically there are two types of endpoints used in `devopness` API:
    1) Resource endpoints:

    **Pattern:**

    `/collection/{resource_id}/[{action}]`

    **Examples:**

    | HTTP Method   | Example                            | Purpose       |
    | -------------:|------------------------------------|---------------|
    | POST          | /projects                          | Create new item
    | GET           | /social-accounts                   | List all items
    | GET           | /social-accounts/{account}/status  | Perform a custom action (`status`) for a single item
    | GET           | /tasks/{id}                        | Get a single item by id
    | PUT           | /applications/{id}                 | Modify an item
    | DELETE        | /processes/{id}                    | Remove an item permanently

    2) Nested resources endpoints:

    Nested resources are used when there is a clear hierarchy between the parent resource and the subresource, or for convenience to make it easy and predcitable on how to filter subresources belonging to a parent resource.
    In `devopness` API design we never nest resources more than 1 level deep + one action related to the child resource or to the relationship between parent and child.

    **Pattern:**

    `/parent-collection/{parent_id}/{child-collection}/{child_id}/[{action}]`

    **Examples:**

    | HTTP Method   | Example                        | Purpose       |
    | -------------:|--------------------------------|---------------|
    | GET           | /projects/{id}/servers         | List all items belonging/linked to the parent resource
    | POST          | /projects/{id}/servers         | Create a new subresource item and link it to the parent object
    | POST          | /parent/{id}/child/{id}/link   | Create a relationship between parent and child object when both items already existed but were not linked.
    | DELETE        | /parent/{id}/child/{id}/unlink | Remove the relationship between parent and child resources, without deleting any item

    ## Expanding objects
    `TO DO:` define the rules for object expansion and document it here

servers:
  - url: http://devopness-api.local
    description: Local Dev server
  - url: https://test-api.devopness.com
    description: Staging server
  - url: https://api.devopness.com
    description: Production server

paths:
  $ref: ./paths.yaml

tags:
  - name: Static Data
    description: |
      Client API applications might need to retrieve possible accepted values to fulfill their forms and allow end users to pick values from a list of valid data.
      All static data that need to be used through `devopness` API client applications is provided through the `/static/*` endpoints.
  - name: Actions
  - name: Applications
  - name: Applications - Deployments
  - name: Applications - Environments
  - name: Applications - SSL Certificates
    description: |
      Throughout the `devopness` documentation the term `SSL Certificate` refers to a public key certificate adhering to `X.509` standard. While TLS is the protocol more used nowadays for web encryption, for historical reasons web encryption is often referred to simply as SSL. A SSL Certificate managed by `devopness` might be used as an HTTPS/SSL/TLS and other internet protocols to establish encrypted connections between client apps (e.g. browsers) and the web application servers managed through `devopness`, but it's not limited to be used for authenticating server's identity.
  - name: Cronjobs/Scheduled Tasks
    description: |
      A cronjob or scheduled task is a scheduled command to be set on one or more project servers to ensure a given routine will be executed on time.
  - name: Daemons/Processes
    description: |
      The terms `process`, `background process` and `daemon` may be used interchangeably in the `devopness` API documentation to denote the same thing: i.e., a computer process that runs behind the scenes without user intervention, detached from TTY (teletype/terminal type) and having no associated console or controlling terminal, therefore prevented from receiving `SIGHUP` on shell termination.
  - name: Deployments
  - name: Environments
  - name: Logs
  - name: Network Rules
  - name: Projects
  - name: Projects - Applications
  - name: Projects - Cronjobs/Scheduled Tasks
    description: |
      A cronjob or scheduled task is a scheduled command to be set on one or more project servers to ensure a given routine will be executed on time.
  - name: Projects - Daemons/Processes
    description: |
      The terms `process`, `background process` and `daemon` may be used interchangeably in the `devopness` API documentation to denote the same thing: i.e., a computer process that runs behind the scenes without user intervention, detached from TTY (teletype/terminal type) and having no associated console or controlling terminal, therefore prevented from receiving `SIGHUP` on shell termination.
  - name: Projects - Deployments
  - name: Projects - Environments
  - name: Projects - Network Rules
  - name: Projects - Servers
  - name: Projects - Services
  - name: Projects - SSH Keys
  - name: Servers
  - name: Services
  - name: Social Accounts
    description: |
      A social account is a third party login/authorization service connected to the current user's account. e.g.: Facebook, Google, GitHub
  - name: Source Providers
    description: |
      A source provider is a Version Control System (VCS)/Source Code Management (SCM) connected to the current user's account. e.g.: BitBucket, GitHub, GitLab
  - name: Source Providers - Repositories
  - name: SSH Keys
  - name: SSL Certificates
    description: |
      Throughout the `devopness` documentation the term `SSL Certificate` refers to a public key certificate adhering to `X.509` standard. While TLS is the protocol more used nowadays for web encryption, for historical reasons web encryption is often referred to simply as SSL. A SSL Certificate managed by `devopness` might be used as an HTTPS/SSL/TLS and other internet protocols to establish encrypted connections between client apps (e.g. browsers) and the web application servers managed through `devopness`, but it's not limited to be used for authenticating server's identity.
  - name: Users

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Some few endpoints do not require authentication, but pretty much anything else will require you to be authenticated.
        To become authenticated you will need to request an API access token through the `/users/login` endpoint.

        ## Using an access token
        Once you have an access token for a given user you can pass it along in the HTTP request header.
        Alternatively, if consuming the API through a web application, the token can be sent in the `AuthToken` HTTPOnly cookie as part of the HTTP request.
  parameters:
    $ref: ./parameters.yaml
  schemas:
    $ref: ./data-models.yaml
  responses:
    $ref: ./responses.yaml
