type: object
properties:
  status:
    type: string
    description: The current status of the action
    enum: ['pending', 'in-progress', 'cancelled', 'completed', 'failed']
    example: 'in-progress'
  type:
    type: string
    description: The action type
    enum: ['create', 'launch', 'setup', 'deploy', 'remove', 'connect']
    example: setup
  total_steps:
    type: integer
    minimum: 0
    maximum: 127
    description: The total number of steps to complete the action
    example: 5
  current_step:
    type: integer
    minimum: 0
    maximum: 127
    description: The current action step being executed
    example: 2
  current_step_message:
    type: string
    description: A message describing the current step being executed
    example: Step 2 of 5
  output:
    type: string
    description: A memo/text with full action output log - when available
  started_at:
    type: string
    format: date-time
    description: The date and time when the action started to be executed (left the `pending/waiting` status)
    example: '2019-09-25 13:49:51'
  completed_at:
    type: string
    format: date-time
    description: The date and time when the action has finished execution
    example: '2019-09-25 13:52:04'
