type: object
properties:
  type:
    $ref: '#/components/schemas/DeploymentType'
  branch:
    type: string
    description: "The name of the branch from which the application source code will be retrieved and deployed. This parameter is ignored when `hash` is provided."
    example: master
  hash:
    type: string
    description: "The commit hash from which the application source code will be retrieved and deployed. When provided `branch` parameter is ignored"
    example: 7ff09b0f2ed07625222f689d1afc29aa322b03a2
  servers:
    type: array
    description: List of servers ids that the deploy will be triggered to
    example: [4321]
    items:
      type: integer
required:
  - type
  - branch
