type: object
properties:
  type:
    $ref: '#/components/schemas/DeploymentType'
  applications:
    description: "The list of applications to be deployed together"
    type: array
    items:
      $ref: '#/components/schemas/DeploymentCreateApplication'
  servers:
    description: "The list of servers to which all `applications` will be deployed to"
    type: array
    items:
      $ref: '#/components/schemas/DeploymentCreateServer'
  environments:
    $ref: '#/components/schemas/EnvironmentLinks'
required:
  - type
  - applications
  - servers
