summary: Create a new variable linked to an application environment
tags:
  - Applications - Environments
parameters:
  - $ref: "#/components/parameters/authHeader"
  - $ref: "#/components/parameters/acceptHeader"
  - $ref: "#/components/parameters/contentTypeHeader"
  - in: path
    name: application_environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Unique id of the application environment
requestBody:
  description: A JSON object containing data for creating a new record of application environment variable
  required: true
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/ApplicationEnvironmentVariableCreate"
responses:
  201:
    description: 'Created'
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ApplicationEnvironmentVariable"
  404:
    $ref: "#/components/responses/NotFound"
