summary: Returns the profile of a member on environment
operationId: getEnvironmentMemberProfile
tags:
  - Environments - Members
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - $ref: '#/components/parameters/pageNumber'
  - $ref: '#/components/parameters/pageSize'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the environment to get members from
  - in: path
    name: user_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the user to get profile information
responses:
  200:
    description: 'Ok'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/EnvironmentMemberProfile'
  404:
    $ref: '#/components/responses/NotFound'
