type: object
properties:
  id:
    type: integer
    description: The ID of the member
    example: 1
  name:
    type: string
    description: Member's full name
    example: John Smith
  email:
    type: string
    format: email
    description: Member's email
    example: member@example.com
required:
  - id
  - name
  - email
