[package]
name = "tetanus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "tetanus"
path = "src/main.rs"

[dependencies]
tetanus-core = { workspace = true }
tetanus-config = { workspace = true }
tetanus-cache = { workspace = true }
tetanus-ast = { workspace = true }
tetanus-graph = { workspace = true }
tetanus-deps = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
serde_yaml = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }

[dependencies.oxc_allocator]
version = "0.151"
