type: object
properties:
  name:
    type: string
    description: Name/short description of the script
    example: Prepare for build project
  source_code:
    type: string
    description: A command line or multiline bash script
    example: echo "Configuring project..." && ./configure
  trigger_type:
    $ref: '#/components/schemas/TriggerType'
  trigger_event:
    $ref: '#/components/schemas/TriggerEvent'
  trigger_order:
    type: integer
    description: The relative order of the script execution in case the event has multiple scripts attached to it
    example: 2
required:
  - name
  - source_code
  - trigger_event
  - trigger_order
  - trigger_type
