type: object
properties:
  id:
    type: integer
    description: The unique id of the given record
    example: 35678964
  application_id:
    type: integer
    description: The unique id of the application that script is linked
    example: 13129876
  user_id:
    type: integer
    description: The unique id of the user that own the script
    example: 86123953
  name:
    type: string
    description: Name/short description of the script
    example: Prepare for build project
  source_code:
    type: string
    description: A command line or multiline bash script
    example: echo "Configuring project..." && ./configure
  trigger_type:
    type: string
    description: The type of event that will trigger the script execution
    enum: [before, after]
    example: "after"
  trigger_event:
    type: string
    description: The application deployment event to which the script is attached
    enum:
      [
        get-new-release,
        install-dependencies,
        activate-new-release,
        remove-old-releases,
      ]
    example: "install-dependencies"
  trigger_order:
    type: integer
    description: The relative order of the script execution in case the event has multiple scripts attached
    example: 2
  created_at:
    type: string
    format: date-time
    description: The date and time when the record was created
    example: "2020-04-16T15:50:48.000000Z"
  updated_at:
    type: string
    format: date-time
    description: The date and time when the record was last updated
    example: "2020-04-16T15:50:48.000000Z"
required:
  - id
  - application_id
  - user_id
  - name
  - source_code
  - trigger_event
  - trigger_order
  - trigger_type
