summary: Update an existing role
operationId: updateRole
tags:
  - Roles
parameters:
  - $ref: "#/components/parameters/acceptHeader"
  - $ref: "#/components/parameters/authHeader"
  - $ref: "#/components/parameters/contentTypeHeader"
  - in: path
    name: role_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the role to update
requestBody:
  description: A JSON object containing role data
  required: true
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/RoleUpdate"
responses:
  204:
    $ref: "#/components/responses/NoContent"
  404:
    $ref: "#/components/responses/NotFound"
  422:
    $ref: "#/components/responses/ValidationError"
