"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

import json
from enum import Enum
from typing import Literal, Self


class ActionType(str, Enum):
    """
    ActionType
    """

    CONFIGURE = "configure"
    CHECK_PROVISIONED = "check_provisioned"
    DELETE = "delete"
    DEPLOY = "deploy"
    GET_STATUS = "get_status"
    PROVISION = "provision"
    RELOAD = "reload"
    RESTART = "restart"
    START = "start"
    STOP = "stop"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionType from a JSON string"""
        return cls(json.loads(json_str))


# The plain version of ActionType
ActionTypePlain = Literal[
    "configure",
    "check_provisioned",
    "delete",
    "deploy",
    "get_status",
    "provision",
    "reload",
    "restart",
    "start",
    "stop",
]
