"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

import json
from enum import Enum
from typing import Literal, Self


class ActionStatus(str, Enum):
    """
    Current item status
    """

    PENDING = "pending"
    WAITING = "waiting"
    SKIPPED = "skipped"
    QUEUED = "queued"
    IN_MINUS_PROGRESS = "in-progress"
    COMPLETED = "completed"
    FAILED = "failed"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionStatus from a JSON string"""
        return cls(json.loads(json_str))


# The plain version of ActionStatus
ActionStatusPlain = Literal[
    "pending",
    "waiting",
    "skipped",
    "queued",
    "in-progress",
    "completed",
    "failed",
]
