"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
    Union,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .action_deployment_commit import (
    ActionDeploymentCommit,
    ActionDeploymentCommitPlain,
)
from .action_deployment_content import (
    ActionDeploymentContent,
    ActionDeploymentContentPlain,
)


class ActionDeploymentData(DevopnessBaseModel):
    """
    ActionDeploymentData

    Attributes:
        release_name (str): The name generated to release created by this deployment
        commit (ActionDeploymentCommit):
        deployment (ActionDeploymentContent):
    """

    release_name: StrictStr = Field(
        description="The name generated to release created by this deployment"
    )
    commit: ActionDeploymentCommit
    deployment: ActionDeploymentContent


class ActionDeploymentDataPlain(TypedDict, total=False):
    """
    Plain version of ActionDeploymentData.
    """

    release_name: Required[str]
    commit: Required[
        Union[
            ActionDeploymentCommit,
            ActionDeploymentCommitPlain,
        ]
    ]
    deployment: Required[
        Union[
            ActionDeploymentContent,
            ActionDeploymentContentPlain,
        ]
    ]
