"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CloudProviderServiceCode(str, Enum):
    """
    The code that uniquely identify this cloud service
    """

    """
    allowed enum values
    """
    AWS_MINUS_EC2 = "aws-ec2"
    AZURE_MINUS_RM = "azure-rm"
    DIGITALOCEAN_MINUS_DROPLET = "digitalocean-droplet"
    GCP_MINUS_GCE = "gcp-gce"
    SELF_MINUS_HOSTED_MINUS_CUSTOM = "self-hosted-custom"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CloudProviderServiceCode from a JSON string"""
        return cls(json.loads(json_str))
