"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List, Optional, TypedDict

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .cloud_provider_service_code import CloudProviderServiceCode
from .cloud_provider_service_region import CloudProviderServiceRegion
from .cloud_provider_service_resource_type import CloudProviderServiceResourceType
from .provider_relation import ProviderRelation


class CloudProviderService(DevopnessBaseModel):
    """
    CloudProviderService

    Attributes:
        code (CloudProviderServiceCode):
        name (str): The full name of the cloud service
        provider (ProviderRelation, optional):
        regions (List[CloudProviderServiceRegion], optional):
        resource_types (List[CloudProviderServiceResourceType], optional):
    """

    code: CloudProviderServiceCode
    name: StrictStr = Field(description="The full name of the cloud service")
    provider: Optional[ProviderRelation] = None
    regions: Optional[List[CloudProviderServiceRegion]] = None
    resource_types: Optional[List[CloudProviderServiceResourceType]] = None


class CloudProviderServiceDict(TypedDict, total=False):
    """
    TypedDict for CloudProviderService.
    """

    code: CloudProviderServiceCode
    name: str
    provider: ProviderRelation
    regions: List[CloudProviderServiceRegion]
    resource_types: List[CloudProviderServiceResourceType]
