"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CloudProviderServiceResourceTypeScope(str, Enum):
    """
    The resource type's scope
    """

    """
    allowed enum values
    """
    GLOBAL = "global"
    REGION = "region"
    ZONE = "zone"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CloudProviderServiceResourceTypeScope from a JSON string"""
        return cls(json.loads(json_str))
