"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CloudOsVersionCode(str, Enum):
    """
    The Operating System distribution and version used in the server/virtual machine instance
    """

    """
    allowed enum values
    """
    CENTOS_7 = "centos_7"
    UBUNTU_18_04 = "ubuntu_18_04"
    UBUNTU_20_04 = "ubuntu_20_04"
    UBUNTU_22_04 = "ubuntu_22_04"
    UBUNTU_24_04 = "ubuntu_24_04"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CloudOsVersionCode from a JSON string"""
        return cls(json.loads(json_str))
