"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CloudProviderPropertyType(str, Enum):
    """
    CloudProviderPropertyType
    """

    """
    allowed enum values
    """
    STRING = "string"
    TEXT = "text"
    INTEGER = "integer"
    BOOLEAN = "boolean"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CloudProviderPropertyType from a JSON string"""
        return cls(json.loads(json_str))
