"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictBool, StrictInt, StrictStr

from .. import DevopnessBaseModel
from .provider_relation import ProviderRelation
from .provider_type import ProviderType
from .user_relation import UserRelation


class CredentialRelation(DevopnessBaseModel):
    """
    CredentialRelation

    Attributes:
        id (int): The unique ID of the credential
        name (str): The name of the credential
        provider (ProviderRelation):
        provider_type (ProviderType):
        provider_type_human_readable (str): The human readable version of the type of the credential
        active (bool): If this credential is active or not
        created_by_user (UserRelation):
        created_at (str): The date and time when the record was created
        updated_at (str): The date and time when the record was last updated
    """

    id: StrictInt = Field(description="The unique ID of the credential")
    name: StrictStr = Field(description="The name of the credential")
    provider: ProviderRelation
    provider_type: ProviderType
    provider_type_human_readable: StrictStr = Field(
        description="The human readable version of the type of the credential"
    )
    active: StrictBool = Field(description="If this credential is active or not")
    created_by_user: UserRelation
    created_at: StrictStr = Field(
        description="The date and time when the record was created"
    )
    updated_at: StrictStr = Field(
        description="The date and time when the record was last updated"
    )


class CredentialRelationDict(TypedDict, total=False):
    """
    TypedDict for CredentialRelation.
    """

    id: int
    name: str
    provider: ProviderRelation
    provider_type: ProviderType
    provider_type_human_readable: str
    active: bool
    created_by_user: UserRelation
    created_at: str
    updated_at: str
