"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
    Union,
)

from .. import DevopnessBaseModel
from .credential_input_settings_credential import (
    CredentialInputSettingsCredential,
    CredentialInputSettingsCredentialPlain,
)


class CredentialInputSettings(DevopnessBaseModel):
    """
    CredentialInputSettings

    Attributes:
        credential (CredentialInputSettingsCredential):
    """

    credential: CredentialInputSettingsCredential


class CredentialInputSettingsPlain(TypedDict, total=False):
    """
    Plain version of CredentialInputSettings.
    """

    credential: Required[
        Union[
            CredentialInputSettingsCredential,
            CredentialInputSettingsCredentialPlain,
        ]
    ]
