"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class CredentialGoogleCloud(DevopnessBaseModel):
    """
    CredentialGoogleCloud

    Attributes:
        service_account_key (str): The JSON key to service account of Google Cloud provider
    """

    service_account_key: StrictStr = Field(
        description="The JSON key to service account of Google Cloud provider"
    )


class CredentialGoogleCloudDict(TypedDict, total=False):
    """
    TypedDict for CredentialGoogleCloud.
    """

    service_account_key: str
