"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class CredentialDigitalOcean(DevopnessBaseModel):
    """
    CredentialDigitalOcean

    Attributes:
        api_token (str): The API token used to authenticate to DigitalOcean
    """

    api_token: StrictStr = Field(
        description="The API token used to authenticate to DigitalOcean"
    )


class CredentialDigitalOceanPlain(TypedDict, total=False):
    """
    Plain version of CredentialDigitalOcean.
    """

    api_token: Required[str]
