"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from .. import DevopnessBaseModel
from .credential_input_settings_credential import CredentialInputSettingsCredential


class CredentialInputSettings(DevopnessBaseModel):
    """
    CredentialInputSettings

    Attributes:
        credential (CredentialInputSettingsCredential):
    """

    credential: CredentialInputSettingsCredential


class CredentialInputSettingsDict(TypedDict, total=False):
    """
    TypedDict for CredentialInputSettings.
    """

    credential: CredentialInputSettingsCredential
