"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictInt

from .. import DevopnessBaseModel
from .credential_provider_type import CredentialProviderType
from .provider_settings import ProviderSettings


class CredentialSetting(DevopnessBaseModel):
    """
    CredentialSetting

    Attributes:
        provider (CredentialProviderType):
        environment_id (int): Numeric ID of the environment to which the network belongs to
        settings (ProviderSettings):
    """

    provider: CredentialProviderType
    environment_id: StrictInt = Field(
        description="Numeric ID of the environment to which the network belongs to"
    )
    settings: ProviderSettings


class CredentialSettingDict(TypedDict, total=False):
    """
    TypedDict for CredentialSetting.
    """

    provider: CredentialProviderType
    environment_id: int
    settings: ProviderSettings
