"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictBool, StrictStr

from .. import DevopnessBaseModel
from .credential_input_settings import CredentialInputSettings
from .provider_code import ProviderCode
from .provider_type import ProviderType


class CredentialEnvironmentCreate(DevopnessBaseModel):
    """
    CredentialEnvironmentCreate

    Attributes:
        name (str): The name of the credential. Must not be greater than 60 characters.
        provider_code (ProviderCode):
        provider_type (ProviderType):
        active (bool): If this credential is active or not.
        settings (CredentialInputSettings):
    """

    name: StrictStr = Field(
        description="The name of the credential. Must not be greater than 60 characters."
    )
    provider_code: ProviderCode
    provider_type: ProviderType
    active: StrictBool = Field(description="If this credential is active or not.")
    settings: CredentialInputSettings


class CredentialEnvironmentCreateDict(TypedDict, total=False):
    """
    TypedDict for CredentialEnvironmentCreate.
    """

    name: str
    provider_code: ProviderCode
    provider_type: ProviderType
    active: bool
    settings: CredentialInputSettings
