"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class CredentialSourceProvider(DevopnessBaseModel):
    """
    CredentialSourceProvider

    Attributes:
        callback_code (str): The temporary code forwarded by the OAuth provider as a parameter to our callback URL
    """

    callback_code: StrictStr = Field(
        description="The temporary code forwarded by the OAuth provider as a parameter to our callback URL"
    )


class CredentialSourceProviderDict(TypedDict, total=False):
    """
    TypedDict for CredentialSourceProvider.
    """

    callback_code: str
