"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

from .credential_aws import CredentialAws
from .credential_digital_ocean import CredentialDigitalOcean
from .credential_google_cloud import CredentialGoogleCloud
from .credential_source_provider import CredentialSourceProvider

#: AnyOf Type
#: Cloud provider credential
CredentialInputSettingsCredential = Union[
    CredentialAws,
    CredentialDigitalOcean,
    CredentialGoogleCloud,
    CredentialSourceProvider,
]
