"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

from .credential_aws import CredentialAws, CredentialAwsPlain
from .credential_azure import CredentialAzure, CredentialAzurePlain
from .credential_digital_ocean import (
    CredentialDigitalOcean,
    CredentialDigitalOceanPlain,
)
from .credential_google_cloud import CredentialGoogleCloud, CredentialGoogleCloudPlain
from .credential_source_provider import (
    CredentialSourceProvider,
    CredentialSourceProviderPlain,
)

#: AnyOf Type
#: Cloud provider credential
CredentialInputSettingsCredential = Union[
    CredentialAws,
    CredentialAzure,
    CredentialDigitalOcean,
    CredentialGoogleCloud,
    CredentialSourceProvider,
]

#: The plain version of CredentialInputSettingsCredential
CredentialInputSettingsCredentialPlain = Union[
    CredentialAwsPlain,
    CredentialAzurePlain,
    CredentialDigitalOceanPlain,
    CredentialGoogleCloudPlain,
    CredentialSourceProviderPlain,
]
