"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    List,
    Optional,
    TypedDict,
)

from pydantic import Field, StrictInt

from .. import DevopnessBaseModel


class DaemonStart(DevopnessBaseModel):
    """
    DaemonStart

    Attributes:
        servers (List[int], optional): List of valid resource IDs
    """

    servers: Optional[List[StrictInt]] = Field(
        default=None, description="List of valid resource IDs"
    )


class DaemonStartPlain(TypedDict, total=False):
    """
    Plain version of DaemonStart.
    """

    servers: Optional[List[int]]
