"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List, Optional, TypedDict

from pydantic import Field, StrictBool, StrictInt, StrictStr

from .. import DevopnessBaseModel
from .environment_type import EnvironmentType
from .resource_summary_item import ResourceSummaryItem
from .team_relation import TeamRelation
from .user_relation import UserRelation


class Environment(DevopnessBaseModel):
    """
    Environment

    Attributes:
        id (int): Unique id of the given record
        type (EnvironmentType):
        type_human_readable (str): The human readable version of the type
        name (str): Environment&#39;s name
        description (str): Environment&#39;s description
        is_archived (bool): Indicates whether the record was archived
        resource_summary (List[ResourceSummaryItem], optional): Summary of the resource
        teams (List[TeamRelation]):
        created_by_user (UserRelation):
        current_user_permissions (List[str]): The list of permissions granted for this role
        created_at (str): The date and time when the record was created
        updated_at (str): The date and time when the record was last updated
    """

    id: StrictInt = Field(description="Unique id of the given record")
    type: EnvironmentType
    type_human_readable: StrictStr = Field(
        description="The human readable version of the type"
    )
    name: StrictStr = Field(description="Environment's name")
    description: Optional[StrictStr] = Field(description="Environment's description")
    is_archived: StrictBool = Field(
        description="Indicates whether the record was archived"
    )
    resource_summary: Optional[List[ResourceSummaryItem]] = Field(
        default=None, description="Summary of the resource"
    )
    teams: List[Optional[TeamRelation]]
    created_by_user: UserRelation
    current_user_permissions: List[StrictStr] = Field(
        description="The list of permissions granted for this role"
    )
    created_at: StrictStr = Field(
        description="The date and time when the record was created"
    )
    updated_at: StrictStr = Field(
        description="The date and time when the record was last updated"
    )


class EnvironmentDict(TypedDict, total=False):
    """
    TypedDict for Environment.
    """

    id: int
    type: EnvironmentType
    type_human_readable: str
    name: str
    description: str
    is_archived: bool
    resource_summary: List[ResourceSummaryItem]
    teams: List[TeamRelation]
    created_by_user: UserRelation
    current_user_permissions: List[str]
    created_at: str
    updated_at: str
