"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

from .hook_outgoing_trigger_when_condition import (
    HookOutgoingTriggerWhenCondition,
    HookOutgoingTriggerWhenConditionPlain,
)
from .trigger_when_condition import TriggerWhenCondition, TriggerWhenConditionPlain

#: OneOf Type
#: HookTriggerWhenConditionsInner
HookTriggerWhenConditionsInner = Union[
    HookOutgoingTriggerWhenCondition,
    TriggerWhenCondition,
]

#: The plain version of HookTriggerWhenConditionsInner
HookTriggerWhenConditionsInnerPlain = Union[
    TriggerWhenConditionPlain,
    HookOutgoingTriggerWhenConditionPlain,
]
