"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Union,
)

#: OneOf Type
#: HookVariableDefaultValueOneOfInner
HookVariableDefaultValueOneOfInner = Union[
    bool,
    float,
    object,
    str,
]

#: The plain version of HookVariableDefaultValueOneOfInner
HookVariableDefaultValueOneOfInnerPlain = HookVariableDefaultValueOneOfInner
