"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Optional,
    Required,
    TypedDict,
    Union,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .action_target_data import ActionTargetData, ActionTargetDataPlain
from .action_target_log_step import ActionTargetLogStep, ActionTargetLogStepPlain


class Log(DevopnessBaseModel):
    """
    Log

    Attributes:
        target (ActionTargetData):
        step (ActionTargetLogStep):
        updated_at (str): The date and time when the requested log record was last updated
    """

    target: Optional[ActionTargetData]
    step: Optional[ActionTargetLogStep]
    updated_at: Optional[StrictStr] = Field(
        description="The date and time when the requested log record was last updated"
    )


class LogPlain(TypedDict, total=False):
    """
    Plain version of Log.
    """

    target: Required[
        Union[
            ActionTargetData,
            ActionTargetDataPlain,
        ]
    ]
    step: Required[
        Union[
            ActionTargetLogStep,
            ActionTargetLogStepPlain,
        ]
    ]
    updated_at: Required[str]
