"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
    Union,
)

from .. import DevopnessBaseModel
from .network_provision_input_settings import (
    NetworkProvisionInputSettings,
    NetworkProvisionInputSettingsPlain,
)
from .server_cloud_service_code import (
    ServerCloudServiceCode,
    ServerCloudServiceCodePlain,
)


class NetworkProvisionInput(DevopnessBaseModel):
    """
    NetworkProvisionInput

    Attributes:
        cloud_service_code (ServerCloudServiceCode):
        settings (NetworkProvisionInputSettings):
    """

    cloud_service_code: ServerCloudServiceCode
    settings: NetworkProvisionInputSettings


class NetworkProvisionInputPlain(TypedDict, total=False):
    """
    Plain version of NetworkProvisionInput.
    """

    cloud_service_code: Required[
        Union[
            ServerCloudServiceCode,
            ServerCloudServiceCodePlain,
        ]
    ]
    settings: Required[
        Union[
            NetworkProvisionInputSettings,
            NetworkProvisionInputSettingsPlain,
        ]
    ]
