"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class OsUsersInner(DevopnessBaseModel):
    """
    OsUsersInner

    Attributes:
        name (str): Operating system username
    """

    name: StrictStr = Field(description="Operating system username")


class OsUsersInnerPlain(TypedDict, total=False):
    """
    Plain version of OsUsersInner.
    """

    name: Required[str]
