"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Optional,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class PipelineSettingsStage(DevopnessBaseModel):
    """
    PipelineSettingsStage

    Attributes:
        value (str, optional):
        human_readable (str, optional):
        hint (str, optional): Descriptive text to help users to know what data is stored in the field and optional extra information on how to enter data to the field
    """

    value: Optional[StrictStr] = None
    human_readable: Optional[StrictStr] = None
    hint: Optional[StrictStr] = Field(
        default=None,
        description="Descriptive text to help users to know what data is stored in the field and optional extra information on how to enter data to the field",
    )


class PipelineSettingsStagePlain(TypedDict, total=False):
    """
    Plain version of PipelineSettingsStage.
    """

    value: Optional[str]
    human_readable: Optional[str]
    hint: Optional[str]
