"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Optional, TypedDict

from pydantic import (
    Field,
    StrictBool,
    StrictStr,
)

from .. import DevopnessBaseModel
from .provider_code import ProviderCode


class ProviderRelation(DevopnessBaseModel):
    """
    ProviderRelation

    Attributes:
        active (bool): Tells if the provider is active or not
        code (ProviderCode):
        code_human_readable (str): Human readable version of provider code
        type (str): Type of provider.
        type_human_readable (str, optional): Human readable version of provider type
    """

    active: StrictBool = Field(description="Tells if the provider is active or not")
    code: ProviderCode
    code_human_readable: StrictStr = Field(
        description="Human readable version of provider code"
    )
    type: StrictStr = Field(description="Type of provider.")
    type_human_readable: Optional[StrictStr] = Field(
        default=None, description="Human readable version of provider type"
    )


class ProviderRelationDict(TypedDict, total=False):
    """
    TypedDict for ProviderRelation.
    """

    active: bool
    code: ProviderCode
    code_human_readable: str
    type: str
    type_human_readable: str
