"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ProviderType(str, Enum):
    """
    Type of provider.
    """

    """
    allowed enum values
    """
    CLOUD_PROVIDER = "cloud_provider"
    SOURCE_PROVIDER = "source_provider"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProviderType from a JSON string"""
        return cls(json.loads(json_str))
