"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ProviderCode(str, Enum):
    """
    The code of the service provider
    """

    """
    allowed enum values
    """
    AWS = "aws"
    BITBUCKET = "bitbucket"
    DIGITALOCEAN = "digitalocean"
    GCP = "gcp"
    GITHUB = "github"
    GITLAB = "gitlab"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProviderCode from a JSON string"""
        return cls(json.loads(json_str))
