"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List, Optional, TypedDict

from pydantic import StrictBool, StrictInt, StrictStr

from .. import DevopnessBaseModel


class ProviderInputSettingsValidation(DevopnessBaseModel):
    """
    ProviderInputSettingsValidation

    Attributes:
        required (bool, optional):
        type (str, optional):
        min (int, optional):
        max (int, optional):
        allowed_values (List[str], optional):
    """

    required: Optional[StrictBool] = None
    type: Optional[StrictStr] = None
    min: Optional[StrictInt] = None
    max: Optional[StrictInt] = None
    allowed_values: Optional[List[StrictStr]] = None


class ProviderInputSettingsValidationDict(TypedDict, total=False):
    """
    TypedDict for ProviderInputSettingsValidation.
    """

    required: bool
    type: str
    min: int
    max: int
    allowed_values: List[str]
