"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class RepositoryTagCommit(DevopnessBaseModel):
    """
    RepositoryTagCommit

    Attributes:
        hash (str): The commit comment&#39;s full hash that uniquely identify it
        url (str): The direct URL for accessing commit details on the provider&#39;s web application
    """

    hash: StrictStr = Field(
        description="The commit comment's full hash that uniquely identify it"
    )
    url: StrictStr = Field(
        description="The direct URL for accessing commit details on the provider's web application"
    )


class RepositoryTagCommitDict(TypedDict, total=False):
    """
    TypedDict for RepositoryTagCommit.
    """

    hash: str
    url: str
