"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .repository_tag_commit import RepositoryTagCommit


class RepositoryTag(DevopnessBaseModel):
    """
    RepositoryTag

    Attributes:
        name (str): The name of the tag
        commit (RepositoryTagCommit):
    """

    name: StrictStr = Field(description="The name of the tag")
    commit: RepositoryTagCommit


class RepositoryTagDict(TypedDict, total=False):
    """
    TypedDict for RepositoryTag.
    """

    name: str
    commit: RepositoryTagCommit
