"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class ServerCommand(DevopnessBaseModel):
    """
    ServerCommand

    Attributes:
        connect_command (str): The Shell Script command to be executed in an existing Linux server in order to connect it to the &#x60;devopness&#x60;
    """

    connect_command: StrictStr = Field(
        description="The Shell Script command to be executed in an existing Linux server in order to connect it to the `devopness`"
    )


class ServerCommandPlain(TypedDict, total=False):
    """
    Plain version of ServerCommand.
    """

    connect_command: Required[str]
