"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

from .cloud_service_settings_aws_ec2 import (
    CloudServiceSettingsAwsEc2,
    CloudServiceSettingsAwsEc2Plain,
)
from .cloud_service_settings_azure_rm import (
    CloudServiceSettingsAzureRm,
    CloudServiceSettingsAzureRmPlain,
)
from .cloud_service_settings_digital_ocean_droplet import (
    CloudServiceSettingsDigitalOceanDroplet,
    CloudServiceSettingsDigitalOceanDropletPlain,
)
from .cloud_service_settings_gcp_gce import (
    CloudServiceSettingsGcpGce,
    CloudServiceSettingsGcpGcePlain,
)
from .cloud_service_settings_self_hosted_custom import (
    CloudServiceSettingsSelfHostedCustom,
    CloudServiceSettingsSelfHostedCustomPlain,
)

#: AnyOf Type
#: The configurations used to cloud service
ServerProvisionInputSettings = Union[
    CloudServiceSettingsAwsEc2,
    CloudServiceSettingsAzureRm,
    CloudServiceSettingsDigitalOceanDroplet,
    CloudServiceSettingsGcpGce,
    CloudServiceSettingsSelfHostedCustom,
]

#: The plain version of ServerProvisionInputSettings
ServerProvisionInputSettingsPlain = Union[
    CloudServiceSettingsAwsEc2Plain,
    CloudServiceSettingsAzureRmPlain,
    CloudServiceSettingsDigitalOceanDropletPlain,
    CloudServiceSettingsGcpGcePlain,
    CloudServiceSettingsSelfHostedCustomPlain,
]
