"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class SocialAccountDisplayableName(str, Enum):
    """
    A formatted version of the `provider` field value, aligned with the provider's name branding
    """

    """
    allowed enum values
    """
    BITBUCKET = "Bitbucket"
    FACEBOOK = "Facebook"
    GITHUB = "GitHub"
    GITLAB = "GitLab"
    GOOGLE = "Google"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SocialAccountDisplayableName from a JSON string"""
        return cls(json.loads(json_str))
