"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List, Optional

from pydantic import Field

from .. import DevopnessBaseModel
from .subscription_plan import SubscriptionPlan


class StaticBillingInfo(DevopnessBaseModel):
    """
    StaticBillingInfo

    Attributes:
        subscription_plans (List[SubscriptionPlan], optional): The list of subscription plans
    """

    subscription_plans: Optional[List[Optional[SubscriptionPlan]]] = Field(
        default=None, description="The list of subscription plans"
    )
