"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    List,
    Optional,
    TypedDict,
    Union,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .variable_targets import VariableTargets, VariableTargetsPlain


class StaticServiceTypeSupportedVersionsInner(DevopnessBaseModel):
    """
    StaticServiceTypeSupportedVersionsInner

    Attributes:
        version (str, optional): The service&#39;s version that is supported
        variable_targets (List[VariableTargets], optional): The list of VariableTarget
    """

    version: Optional[StrictStr] = Field(
        default=None, description="The service's version that is supported"
    )
    variable_targets: Optional[List[VariableTargets]] = Field(
        default=None, description="The list of VariableTarget"
    )


class StaticServiceTypeSupportedVersionsInnerPlain(TypedDict, total=False):
    """
    Plain version of StaticServiceTypeSupportedVersionsInner.
    """

    version: Optional[str]
    variable_targets: Optional[
        List[
            Union[
                VariableTargets,
                VariableTargetsPlain,
            ]
        ]
    ]
