"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

from .subnet_provision_input_settings_aws import (
    SubnetProvisionInputSettingsAws,
    SubnetProvisionInputSettingsAwsPlain,
)
from .subnet_provision_input_settings_azure import (
    SubnetProvisionInputSettingsAzure,
    SubnetProvisionInputSettingsAzurePlain,
)
from .subnet_provision_input_settings_digital_ocean import (
    SubnetProvisionInputSettingsDigitalOcean,
    SubnetProvisionInputSettingsDigitalOceanPlain,
)
from .subnet_provision_input_settings_gcp import (
    SubnetProvisionInputSettingsGcp,
    SubnetProvisionInputSettingsGcpPlain,
)

#: OneOf Type
#: SubnetProvisionInputSettings
SubnetProvisionInputSettings = Union[
    SubnetProvisionInputSettingsAws,
    SubnetProvisionInputSettingsAzure,
    SubnetProvisionInputSettingsDigitalOcean,
    SubnetProvisionInputSettingsGcp,
]

#: The plain version of SubnetProvisionInputSettings
SubnetProvisionInputSettingsPlain = Union[
    SubnetProvisionInputSettingsAwsPlain,
    SubnetProvisionInputSettingsAzurePlain,
    SubnetProvisionInputSettingsDigitalOceanPlain,
    SubnetProvisionInputSettingsGcpPlain,
]
