"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Optional, TypedDict

from pydantic import StrictBool, StrictStr

from .. import DevopnessBaseModel


class SubscriptionPlan(DevopnessBaseModel):
    """
    SubscriptionPlan

    Attributes:
        provider_plan_id (str, optional):
        human_readable (str, optional):
        allow_subscriptions (bool, optional):
    """

    provider_plan_id: Optional[StrictStr] = None
    human_readable: Optional[StrictStr] = None
    allow_subscriptions: Optional[StrictBool] = None


class SubscriptionPlanDict(TypedDict, total=False):
    """
    TypedDict for SubscriptionPlan.
    """

    provider_plan_id: str
    human_readable: str
    allow_subscriptions: bool
