"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Optional,
    TypedDict,
)

from pydantic import StrictBool, StrictStr

from .. import DevopnessBaseModel


class SubscriptionPlan(DevopnessBaseModel):
    """
    SubscriptionPlan

    Attributes:
        provider_plan_id (str, optional):
        human_readable (str, optional):
        allow_subscriptions (bool, optional):
    """

    provider_plan_id: Optional[StrictStr] = None
    human_readable: Optional[StrictStr] = None
    allow_subscriptions: Optional[StrictBool] = None


class SubscriptionPlanPlain(TypedDict, total=False):
    """
    Plain version of SubscriptionPlan.
    """

    provider_plan_id: Optional[str]
    human_readable: Optional[str]
    allow_subscriptions: Optional[bool]
