"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    List,
    Optional,
    TypedDict,
    Union,
)

from .. import DevopnessBaseModel
from .triggered_action_stats import TriggeredActionStats, TriggeredActionStatsPlain
from .triggered_action_summary import (
    TriggeredActionSummary,
    TriggeredActionSummaryPlain,
)


class TriggeredActions(DevopnessBaseModel):
    """
    TriggeredActions

    Attributes:
        summary (TriggeredActionSummary, optional):
        operations (List[TriggeredActionStats], optional):
    """

    summary: Optional[TriggeredActionSummary] = None
    operations: Optional[List[TriggeredActionStats]] = None


class TriggeredActionsPlain(TypedDict, total=False):
    """
    Plain version of TriggeredActions.
    """

    summary: Optional[
        Union[
            TriggeredActionSummary,
            TriggeredActionSummaryPlain,
        ]
    ]
    operations: Optional[
        List[
            Union[
                TriggeredActionStats,
                TriggeredActionStatsPlain,
            ]
        ]
    ]
