"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Union

#: AnyOf Type
#: TriggerWhenConditionAcceptedValuesInner
TriggerWhenConditionAcceptedValuesInner = Union[
    bool,
    float,
    int,
    str,
]

#: The plain version of TriggerWhenConditionAcceptedValuesInner
TriggerWhenConditionAcceptedValuesInnerPlain = TriggerWhenConditionAcceptedValuesInner
