"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Optional,
    TypedDict,
    Union,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .triggered_action_summary import (
    TriggeredActionSummary,
    TriggeredActionSummaryPlain,
)


class TriggeredActionStats(DevopnessBaseModel):
    """
    TriggeredActionStats

    Attributes:
        resource_type (str, optional): Type of resource used in the action
        action_type (str, optional): Type of action
        resource_type_human_readable (str, optional): Human readable version of the resource type
        action_type_human_readable (str, optional): Type of action human readable
        summary (TriggeredActionSummary, optional):
    """

    resource_type: Optional[StrictStr] = Field(
        default=None, description="Type of resource used in the action"
    )
    action_type: Optional[StrictStr] = Field(default=None, description="Type of action")
    resource_type_human_readable: Optional[StrictStr] = Field(
        default=None, description="Human readable version of the resource type"
    )
    action_type_human_readable: Optional[StrictStr] = Field(
        default=None, description="Type of action human readable"
    )
    summary: Optional[TriggeredActionSummary] = None


class TriggeredActionStatsPlain(TypedDict, total=False):
    """
    Plain version of TriggeredActionStats.
    """

    resource_type: Optional[str]
    action_type: Optional[str]
    resource_type_human_readable: Optional[str]
    action_type_human_readable: Optional[str]
    summary: Optional[
        Union[
            TriggeredActionSummary,
            TriggeredActionSummaryPlain,
        ]
    ]
