"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List, Optional, TypedDict

from .. import DevopnessBaseModel
from .triggered_action_stats import TriggeredActionStats
from .triggered_action_summary import TriggeredActionSummary


class TriggeredActions(DevopnessBaseModel):
    """
    TriggeredActions

    Attributes:
        summary (TriggeredActionSummary, optional):
        operations (List[TriggeredActionStats], optional):
    """

    summary: Optional[TriggeredActionSummary] = None
    operations: Optional[List[TriggeredActionStats]] = None


class TriggeredActionsDict(TypedDict, total=False):
    """
    TypedDict for TriggeredActions.
    """

    summary: TriggeredActionSummary
    operations: List[TriggeredActionStats]
