"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Optional, Union

from pydantic import Field, StrictFloat, StrictInt

from .. import DevopnessBaseModel


class UserTeamStats(DevopnessBaseModel):
    """
    UserTeamStats

    Attributes:
        owner_of (float, optional): Total number of teams that user has access to, as owner.
        member_of (float, optional): Total number of teams that user has access to, as team member.
    """

    owner_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of teams that user has access to, as owner.",
    )
    member_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of teams that user has access to, as team member.",
    )
