"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import List

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel
from .static_billing_info import StaticBillingInfo


class UserProfileOptions(DevopnessBaseModel):
    """
    UserProfileOptions

    Attributes:
        billing (StaticBillingInfo):
        languages (List[str]): Supported languages
        timezones (List[str]): Supported time zones
    """

    billing: StaticBillingInfo
    languages: List[StrictStr] = Field(description="Supported languages")
    timezones: List[StrictStr] = Field(description="Supported time zones")
