"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Optional, TypedDict, Union

from pydantic import Field, StrictFloat, StrictInt

from .. import DevopnessBaseModel


class UserEnvironmentStats(DevopnessBaseModel):
    """
    UserEnvironmentStats

    Attributes:
        owner_of (float, optional): Total number of environments that user has access to, as owner.
        member_of (float, optional): Total number of environments that user has access to, as team member.
    """

    owner_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of environments that user has access to, as owner.",
    )
    member_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of environments that user has access to, as team member.",
    )


class UserEnvironmentStatsDict(TypedDict, total=False):
    """
    TypedDict for UserEnvironmentStats.
    """

    owner_of: float
    member_of: float
