"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import Optional

from .. import DevopnessBaseModel
from .subscription import Subscription


class UserBilling(DevopnessBaseModel):
    """
    UserBilling

    Attributes:
        active_subscription (Subscription):
    """

    active_subscription: Optional[Subscription]
