"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import TypedDict

from .. import DevopnessBaseModel
from .triggered_actions import TriggeredActions
from .user_environment_stats import UserEnvironmentStats
from .user_project_stats import UserProjectStats
from .user_team_stats import UserTeamStats


class UserActivity(DevopnessBaseModel):
    """
    UserActivity

    Attributes:
        projects (UserProjectStats):
        environments (UserEnvironmentStats):
        teams (UserTeamStats):
        triggered_actions (TriggeredActions):
    """

    projects: UserProjectStats
    environments: UserEnvironmentStats
    teams: UserTeamStats
    triggered_actions: TriggeredActions


class UserActivityDict(TypedDict, total=False):
    """
    TypedDict for UserActivity.
    """

    projects: UserProjectStats
    environments: UserEnvironmentStats
    teams: UserTeamStats
    triggered_actions: TriggeredActions
