"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Optional,
    TypedDict,
    Union,
)

from pydantic import Field, StrictFloat, StrictInt

from .. import DevopnessBaseModel


class UserProjectStats(DevopnessBaseModel):
    """
    UserProjectStats

    Attributes:
        owner_of (float, optional): Total number of projects that user has access to, as owner.
        member_of (float, optional): Total number of projects that user has access to, as team member.
    """

    owner_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of projects that user has access to, as owner.",
    )
    member_of: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total number of projects that user has access to, as team member.",
    )


class UserProjectStatsPlain(TypedDict, total=False):
    """
    Plain version of UserProjectStats.
    """

    owner_of: Optional[float]
    member_of: Optional[float]
