"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class UserRefreshToken(DevopnessBaseModel):
    """
    UserRefreshToken

    Attributes:
        refresh_token (str): A token to be used after the original access token has expired, to issue a new token without requiring a new request to the /users/login endpoint.
    """

    refresh_token: StrictStr = Field(
        description="A token to be used after the original access token has expired, to issue a new token without requiring a new request to the /users/login endpoint."
    )


class UserRefreshTokenPlain(TypedDict, total=False):
    """
    Plain version of UserRefreshToken.
    """

    refresh_token: Required[str]
