"""
Devopness API Python SDK - Painless essential DevOps to everyone

Note:
    This is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
"""

from typing import (
    Required,
    TypedDict,
)

from pydantic import Field, StrictStr

from .. import DevopnessBaseModel


class UserUrl(DevopnessBaseModel):
    """
    UserUrl

    Attributes:
        billing_management_url (str): The URL leading to a billing management page
    """

    billing_management_url: StrictStr = Field(
        description="The URL leading to a billing management page"
    )


class UserUrlPlain(TypedDict, total=False):
    """
    Plain version of UserUrl.
    """

    billing_management_url: Required[str]
