[package]
name = "tetanus-graph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tetanus-core = { workspace = true }
serde = { workspace = true }

[features]
default = []
oxigraph = ["dep:oxigraph"]
helixdb = ["dep:helix-db"]

[dependencies.oxigraph]
version = "0.5"
optional = true

[dependencies.helix-db]
version = "3.0"
optional = true
