summary: Add a hook to an application
operationId: addHookToApplication
tags:
  - Applications - Hooks
parameters:
  - $ref: "#/components/parameters/acceptHeader"
  - $ref: "#/components/parameters/authHeader"
  - $ref: "#/components/parameters/contentTypeHeader"
  - in: path
    name: application_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Unique id of the application
requestBody:
  description: A JSON object containing application hook data
  required: true
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/HookCreate"
responses:
  201:
    description: "Created"
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Hook"
  403:
    $ref: "#/components/responses/Forbidden"
  404:
    $ref: "#/components/responses/NotFound"
