summary: Return a list of all tasks belonging to a project
tags:
  - Projects - Cronjobs/Scheduled Tasks
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - in: path
    name: id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the project to get tasks from
responses:
  200:
    description: 'Ok'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Tasks'
