// tslint:disable
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * The current status of the action
     * @type {string}
     * @memberof Action
     */
    status?: ActionStatusEnum;
    /**
     * The action type
     * @type {string}
     * @memberof Action
     */
    type?: ActionTypeEnum;
    /**
     * The total number of steps to complete the action
     * @type {number}
     * @memberof Action
     */
    total_steps?: number;
    /**
     * The current action step being executed
     * @type {number}
     * @memberof Action
     */
    current_step?: number;
    /**
     * A message describing the current step being executed
     * @type {string}
     * @memberof Action
     */
    current_step_message?: string;
    /**
     * A memo/text with full action output log - when available
     * @type {string}
     * @memberof Action
     */
    output?: string;
    /**
     * The date and time when the action started to be executed (left the `pending/waiting` status)
     * @type {string}
     * @memberof Action
     */
    started_at?: string;
    /**
     * The date and time when the action has finished execution
     * @type {string}
     * @memberof Action
     */
    completed_at?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ActionStatusEnum {
    Pending = 'pending',
    InProgress = 'in-progress',
    Cancelled = 'cancelled',
    Completed = 'completed',
    Failed = 'failed'
}
/**
    * @export
    * @enum {string}
    */
export enum ActionTypeEnum {
    Create = 'create',
    Launch = 'launch',
    Setup = 'setup',
    Deploy = 'deploy',
    Remove = 'remove',
    Connect = 'connect'
}



