// tslint:disable
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeploymentCreateApplication
 */
export interface DeploymentCreateApplication {
    /**
     * Numeric ID of the application
     * @type {number}
     * @memberof DeploymentCreateApplication
     */
    id: number;
    /**
     * The applications\'s name
     * @type {string}
     * @memberof DeploymentCreateApplication
     */
    name: string;
    /**
     * The name of the branch from which the source code should be retrieved and deployed
     * @type {string}
     * @memberof DeploymentCreateApplication
     */
    branch: string;
    /**
     * The commit\'s full hash that uniquely identify a commit. Required when re-deploying
     * @type {string}
     * @memberof DeploymentCreateApplication
     */
    hash?: string;
}


