/* eslint-disable */
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EnvironmentLinkItem
 */
export interface EnvironmentLinkItem {
    /**
     * The environment\'s unique id
     * @type {string}
     * @memberof EnvironmentLinkItem
     */
    id: string;
    /**
     * The environment\'s name
     * @type {string}
     * @memberof EnvironmentLinkItem
     */
    name: string;
    /**
     * The list of IDs of servers to which the service action must be performed
     * @type {Array<number>}
     * @memberof EnvironmentLinkItem
     */
    servers: Array<number>;
}


