// tslint:disable
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Optional error object containing details of the server error
 * @export
 * @interface ErrorErrors
 */
export interface ErrorErrors {
    /**
     * Error message specific to each field included in the errors object
     * @type {Array}
     * @memberof ErrorErrors
     */
    field_name?: Array;
}


