// tslint:disable
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProcessCreate
 */
export interface ProcessCreate {
    /**
     * The name entered by the user (or auto-generated by `devopness`) to uniquely identify the process
     * @type {string}
     * @memberof ProcessCreate
     */
    name: string;
    /**
     * The command line to be executed to start the process
     * @type {string}
     * @memberof ProcessCreate
     */
    command: string;
    /**
     * The working directory where the process will be relative to when performing disk i/o
     * @type {string}
     * @memberof ProcessCreate
     */
    working_directory: string;
    /**
     * The number of process instances of the program to run simultaneously
     * @type {number}
     * @memberof ProcessCreate
     */
    process_count: number;
    /**
     * The name of the Unix user on behalf of which the process will run
     * @type {string}
     * @memberof ProcessCreate
     */
    run_as_user: string;
    /**
     * Indicates if the command was auto_generated by `devopness` itself
     * @type {boolean}
     * @memberof ProcessCreate
     */
    auto_generated?: boolean;
}


