// tslint:disable
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServerConnect
 */
export interface ServerConnect {
    /**
     * Output message indicating success or failure
     * @type {string}
     * @memberof ServerConnect
     */
    message: string;
}


