/* eslint-disable */
/**
 * devopness API
 * Devopness API - Painless essential DevOps to everyone 
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceOperation
 */
export interface ServiceOperation {
    /**
     * Optional list of additional parameters to forward to yhe service operation
     * @type {string}
     * @memberof ServiceOperation
     */
    params?: string;
}


