summary: 'Returns a list of all network rules belonging to a environment'
operationId: listEnvironmentNetworkRules
tags:
  - Environments - Network Rules
parameters:
  - $ref: '#/components/parameters/acceptHeader'
  - $ref: '#/components/parameters/authHeader'
  - $ref: '#/components/parameters/contentTypeHeader'
  - $ref: '#/components/parameters/pageNumber'
  - $ref: '#/components/parameters/pageSize'
  - in: path
    name: environment_id
    example: 1
    schema:
      type: integer
      minimum: 1
    required: true
    description: Numeric ID of the environment to get network rules from
responses:
  200:
    description: 'Ok'
    headers:
      Link:
        schema:
          type: string
        description: Link header with `first`, `last`, `previous` and `next` page's links
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/NetworkRules'
