name: Check Spelling

on:
  pull_request_target:
    # triggers on `pull_request_target` as this is a fork-based repository
    # for security reasons, `npm` or other code execution jobs must not
    # be executed on this workflow
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - docs/**

jobs:
  cspell:
    name: check_spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check spelling
        run: |
          git diff --name-only -r HEAD~1 HEAD | npx cspell --config .github/cspell.json --file-list stdin
