name: CI - SDK Python
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

defaults:
  run:
    working-directory: packages/sdks/python

jobs:
  detect-changes:
    name: Detect changes in SDK-Python
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes:
              - 'packages/sdks/common/**'
              - 'packages/sdks/python/**'

  build:
    name: Build SDK-Python
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changes == 'true' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python:
          - 3.13
          - 3.12
          - 3.11
        os:
          - ubuntu-latest

    env:
      PYTHON_VERSION: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: make build-image

      - name: Build SDK - Python
        run: make build-sdk-python

      - name: Lint SDK - Python
        run: make lint

      - name: Test SDK - Python
        run: make test-unit

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.repository == 'devopness/devopness'
        with:
          commit_message: 'docs: Update auto generated models'
          file_pattern: 'packages/sdks/python/*'
          commit_user_name: ${{ vars.DEVOPNESS_AUTOMATIONS_USERNAME }}
          commit_user_email: ${{ vars.DEVOPNESS_AUTOMATIONS_EMAIL }}

  verify-build:
    name: Verify build of SDK-Python
    needs: [build, detect-changes]
    if: success() || failure()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Fail if build did not succeed
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
            echo "❌ Build job failed or was cancelled"
            exit 1
          fi

          echo "✅ Build job succeeded"
