name: "CLA Assistant"

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize
  workflow_call:

jobs:
  check_cla_signatures:
    name: Check CLA signatures
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure PR author has signed CLA"
        if: >
          github.event.comment.body == 'recheck' ||
          github.event.comment.body == 'I have read the CLA document and I hereby sign the CLA' ||
          github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.2
        env:
          # CLA Action uses this in-built GitHub token to make the API calls for interacting with GitHub.
          # It is built into Github Actions and does not need to be manually specified in your secrets store.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The token below should have repo scope (classic) or read and write access to code (fine-grained tokens) to enable access to the remote repository where the signatures are being stored; and must be manually added by you in the organization's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_CONFIG_PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/v1.0.0/cla.json"
          path-to-document: "https://github.com/devopness/.github/blob/main/CLA.md"
          allowlist: dependabot[bot],devopness-automations
          # branch should not be protected
          branch: "main"
          remote-organization-name: "devopness"
          remote-repository-name: "clabot-config"
          lock-pullrequest-aftermerge: false
          custom-pr-sign-comment: "I have read the CLA document and I hereby sign the CLA"
          custom-notsigned-prcomment: |
            <br/>Thanks 💖 for your submission!<br/>
            We ask that $you sign our [Contributor License Agreement](https://github.com/devopness/.github/blob/main/CLA.md) before we can accept your contribution.<br/>
            You can sign the CLA by adding a comment below using this text:
