name: "CLA Assistant"

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  cla_assistant:
    name: CLA Assistant
    uses: devopness/devopness/.github/workflows/cla-assistant.yml@main
    secrets: inherit
