name: "Validate CLA Signature - PR"

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  check_cla_signatures:
    name: Check CLA signatures
    uses: devopness/devopness/.github/workflows/cla-assistant.yml@main
    secrets: inherit
