name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3 #May not be the latest version
      with:
        configuration-path: .github/labeler-issue.yml
        not-before: 2023-11-25T00:00:00Z
        enable-versioned-regex: 0
        include-title: 0
        include-body: 1
        repo-token: ${{ github.token }}
