name: Labeler - PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label PR - Triage
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label PR - Step
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler-pr.yml
          sync-label: true
