name: "Lint PR"

on:
  pull_request_target:
    # triggers on `pull_request_target` as this is a fork-based repository
    # for security reasons, `npm` or other code execution jobs must not
    # be executed on this workflow
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
