name: Release Packages

on:
  workflow_dispatch:
  push:
    paths:
      - packages/**/src/**
      - packages/**/package.json
    branches:
      - main
      - "*.x" # maintenance releases

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci --ignore-scripts
      - name: Create Release Pull Request or Publish Packages
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


