name: SDK JavaScript - CI
on:
  pull_request:
    paths:
      - packages/sdks/javascript/**

defaults:
  run:
    working-directory: packages/sdks/javascript

jobs:
  build:
    name: Build SDK-JS

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          persist-credentials: true
          fetch-depth: 0

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm ci

      - name: build
        run: npm run build-api-models

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.repository == 'devopness/devopness'
        with:
          commit_message: "docs: Update auto generated models"
          file_pattern: "packages/sdks/javascript/*"
          commit_user_name: devopness-automations
          commit_user_email: automations@devopness.com
