name: UI React - Release
on:
  push:
    paths:
      - packages/ui/react/src/**
      - packages/ui/react/package.json
    branches:
      - main
      - "*.x" # maintenance releases

defaults:
  run:
    working-directory: packages/ui/react

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npx semantic-release@22.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
